docs/_docs/development/built-in-activities.md

Manoj please review and comment.

Issue #9: major enhancement

---

mdw-common/build.gradle
mdw-common/src/META-INF/mdw/spring/application-context.xml
mdw-hub/build.gradle
mdw-services/build.gradle
mdw-services/src/com/centurylink/mdw/services/pooling/MDWConnectionPool.java
mdw-workflow/assets/com/centurylink/mdw/tests/cloud/.mdw/versions
mdw-workflow/assets/com/centurylink/mdw/tests/cloud/testContext.spring
mdw-workflow/assets/com/centurylink/mdw/tests/services/.mdw/versions
mdw-workflow/assets/com/centurylink/mdw/tests/services/serviceContext.spring
mdw-workflow/assets/com/centurylink/mdw/tests/tasks/.mdw/versions
mdw-workflow/assets/com/centurylink/mdw/tests/tasks/taskContext.spring

This contains some disruptive changes, such as build.gradle changes, and also changes in application-context.xml which will also require other teams declaring their own beans to make changes to their spring files.

Issue #172

---

mdw-hub/web/js/ui/chart.js
mdw-hub/web/js/workflow/processes.js
mdw-hub/web/ui/chart.html
mdw-hub/web/workflow/chartTypes.html

Hi Don,
I have fixed **Fix Chart Type selection #163**. Kindly review it.

Issue 163 vimala nagarja ctl

---

mdw-hub/web/js/ui/chart.js

changes for issue# 186

---

mdw-common/src/com/centurylink/mdw/constant/PropertyNames.java
mdw-common/src/com/centurylink/mdw/dataaccess/DatabaseAccess.java
mdw-common/src/com/centurylink/mdw/dataaccess/RetryableTransaction.java
mdw-services/src/com/centurylink/mdw/service/data/process/EngineDataAccessDB.java
mdw-services/src/com/centurylink/mdw/services/process/ProcessExecutor.java
mdw-services/src/com/centurylink/mdw/services/process/ProcessExecutorImpl.java

Issue #116

---

mdw-services/src/com/centurylink/mdw/timer/cleanup/ProcessCleanup.java
mdw/database/Cleanup-Runtime.sql
mdw/database/mysql_cleanup.sql

committed the code for issue 168. Mysql cleanup script added

---

mdw-common/src/com/centurylink/mdw/util/file/FileHelper.java
mdw-services/src/com/centurylink/mdw/timer/cleanup/ProcessCleanup.java
mdw-services/src/com/centurylink/mdw/timer/cleanup/ScriptRunner.java
mdw-workflow/assets/com/centurylink/mdw/mysql/.mdw/versions
mdw-workflow/assets/com/centurylink/mdw/mysql/Cleanup-Runtime.sql
mdw-workflow/assets/com/centurylink/mdw/testing/AutoTestWebSocketClient.java
mdw/database/mysql_cleanup.sql

Please see if we can do any performance improvements

Issue 168 manoj

---

mdw-hub/web/js/ui/chart.js

Show process name in tool tip of Charts #185

---

mdw-hub/src/com/centurylink/mdw/hub/servlet/LoginServlet.java
mdw-hub/web/auth/afLogin.html
mdw-hub/web/auth/ctLogin.html

Auth Error messages-Issue #238

---

mdw-common/src/com/centurylink/mdw/dataaccess/db/UserDataAccessDb.java
mdw-common/src/com/centurylink/mdw/model/user/User.java
mdw-common/src/com/centurylink/mdw/model/user/Workgroup.java
mdw-hub/web/groups/groupAttributes.html
mdw-hub/web/groups/groupForm.html
mdw-hub/web/js/groups.js
mdw-hub/web/js/users.js
mdw-hub/web/js/workflow/solutions.js
mdw-hub/web/solutions/solAttributes.html
mdw-hub/web/solutions/solutionForm.html
mdw-hub/web/users/userAttributes.html
mdw-hub/web/users/userForm.html
mdw-services/src/com/centurylink/mdw/service/data/task/UserGroupCache.java
mdw-services/src/com/centurylink/mdw/service/data/user/UserDataAccess.java

Issue 289 manoj

---

mdw-hub/web/js/ui/configurator.js
mdw-hub/web/ui/widgets/link.html

issue #240 changes

---

mdw-common/src/com/centurylink/mdw/dataaccess/file/VcsArchiver.java

Remove Archive directory creation from Import

---

mdw-hub/web/js/tasks/tasks.js

Retain filter selections in the MDWHub task list #364

---

mdw-common/src/com/centurylink/mdw/cache/impl/PackageCache.java
mdw-services/src/com/centurylink/mdw/services/cache/CacheRegistration.java

Startup validation of framework asset packages #378

---

mdw-hub/web/assets/asset.html
mdw-hub/web/js/assets.js
mdw-hub/web/js/tasks/tasks.js

#375 Task instances link from template view page

---

mdw-services/src/com/centurylink/mdw/service/data/process/EngineDataAccess.java
mdw-services/src/com/centurylink/mdw/service/data/process/EngineDataAccessCache.java
mdw-services/src/com/centurylink/mdw/service/data/process/EngineDataAccessDB.java
mdw-services/src/com/centurylink/mdw/services/process/ProcessExecutor.java
mdw-services/src/com/centurylink/mdw/services/process/ProcessExecutorImpl.java
mdw-workflow/src/com/centurylink/mdw/workflow/adapter/ObjectAdapterActivity.java
mdw-workflow/src/com/centurylink/mdw/workflow/adapter/TextAdapterActivity.java

#420 changes

---

mdw-common/src/com/centurylink/mdw/model/workflow/ProcessInstance.java
mdw-common/src/com/centurylink/mdw/model/workflow/ProcessList.java
mdw-common/src/com/centurylink/mdw/util/StringHelper.java

#417 fixes

---

mdw-common/src/com/centurylink/mdw/cli/Convert.java

mdw cli fix issue_737: biswa 

---

mdw-services/src/com/centurylink/mdw/services/event/EventServicesImpl.java
mdw-services/src/com/centurylink/mdw/services/process/ProcessExecutorImpl.java

issue #744

---

docs/_docs/guides/configuration.md
mdw-common/build.gradle
mdw-common/src/com/centurylink/mdw/cli/DbInfo.java
mdw-workflow/assets/com/centurylink/mdw/base/.mdw/versions
mdw-workflow/assets/com/centurylink/mdw/base/StuckActivities.java

commit for issue 772 and 769 : Biswa

---

mdw-common/src/com/centurylink/mdw/constant/PropertyNames.java
mdw-workflow/src/com/centurylink/mdw/workflow/adapter/http/HttpServiceAdapter.java
mdw/config/mdw.yaml

issue 828 timeout values for rest adapter : Biswa

---

mdw-services/src/com/centurylink/mdw/services/process/ActivityLogger.java
mdw-services/src/com/centurylink/mdw/services/process/BaseActivity.java

Fix for issue #846

---

mdw-common/src/com/centurylink/mdw/soccom/SoccomMessage.java

fix for issue #850

---

mdw-services/src/com/centurylink/mdw/services/test/TestCaseScript.java

Please review....I ran several debugging sessions to validate algorithm but you never know.  In any case, if there's no need to split the groovy script due to size, it works the same as currently.
Bottom line it doesn't break any existing functionality since the whole thing used to fail if script (expected yaml file) was too large.

fix for issue #849

---

mdw-services/src/com/centurylink/mdw/services/test/TestCaseScript.java

fix for issue #853

---

mdw-common/src/com/centurylink/mdw/app/ApplicationContext.java
mdw-hub/src/com/centurylink/mdw/hub/MdwMain.java

Fix for issue #856

---

mdw-common/src/com/centurylink/mdw/model/variable/VariableInstance.java
mdw-common/src/com/centurylink/mdw/sync/SyncExpressionEvaluator.java

fix for issue #858
